<%--
  Created by IntelliJ IDEA.
  User: umashanthi
  Date: Jan 31, 2011
  Time: 11:58:33 PM
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head><title>Simple jsp page</title></head>
<body>

Place your content here
<script src="webtoolkit.aim.js" type="text/javascript"><!--mce:0--></script>
<script type="text/javascript"><!--mce:1--></script>

<form action="upload.jsp" method="post">

    <div><label>Name:</label>
        <input name="form[name]" type="text"/></div>


    <div><label>File:</label>
        <input name="form[file]" type="file"/></div>


    <div>
        <input type="submit" value="SUBMIT"/></div>

</form>
<hr/>

<div># of submited forms: <span id="nr">0</span></div>


<div>last submit response (generated by form action - index.php file):
</div>


</body>
</html>